### ISSUE TITLE
About Client

### ISSUE THREAD

**Issue by YukiChiyoda** [YukiChiyoda/TuringTest#1]
@Cheny233 
---
在`main.qml`的**Line35**：
```
answer0Text.text = json["Data"][0]["Text"]
answer1Text.text = json["Data"][1]["Text"]
```
我们的答案数量是不定的..如果在运行中添加标签组件不方便的话，那就预先多放几个备用吧。至少4个。
---
另外，在`README.md`表格中`参数`即为字段名，现已更正。请按照一般的GET方法调用即可。
---
再者，请留点时间给我们`上机测试`......`问题数据库`还没有找技术部的人打工录入......以及五一假期要做好`找志愿者`和`借电脑`的工作......

**Comment by Cheny233** [comment]
玩家客户端中应如何向服务端发送答案并获得反馈，并没有清晰的字段名。

**Comment by YukiChiyoda** [comment]
参照'README.md'中表格

|字段|描述|
|:---:|:---:|
|text|作答内容|

即：
`http://job.hituring.cn:233/push.go?text=[作答内容]`

另一GET同理

**Comment by Cheny233** [comment]
`http://101.34.210.66:233/answer.go?text=[作答内容]`将返回-1，而不是期望的0或1，</br>而`http://101.34.210.66:233/answer.go?flag=[作答内容]`则会一直返回0，所以无法得知如何从服务端获取玩家的答案是否正确

**Comment by YukiChiyoda** [comment]
喵的，游园会取消了
